---
- name: Install VirtualBMC and Open Required Ports
  hosts: dixie-flatline.aus.redhat.com
  become: yes
  tasks:
    - name: Install VirtualBMC using pip
      pip:
        name: virtualbmc
        state: present
        executable: pip3

    - name: Open VirtualBMC daemon port (50891/tcp)
      firewalld:
        port: 50891/tcp
        permanent: yes
        state: enabled

    - name: Reload firewall rules
      command: firewall-cmd --reload

