---
- name: Configure VirtualBMC Instances
  hosts: dixie-flatline.aus.redhat.com
  become: yes
  vars:
    vbmc_nodes:
      - name: ctrl-1.aus.redhat.com
        port: 623
      - name: ctrl-2.aus.redhat.com
        port: 624
      - name: ctrl-3.aus.redhat.com
        port: 625
  tasks:
    - name: Add VirtualBMC instances
      command: /usr/local/bin/vbmc add {{ item.name }} --port {{ item.port }}
      loop: "{{ vbmc_nodes }}"

    - name: Start VirtualBMC instances
      command: /usr/local/bin/vbmc start {{ item.name }}
      loop: "{{ vbmc_nodes }}"

